### ISSUE TITLE
Docker file issue

### ISSUE THREAD

**Issue by koteshbhupathi** [jenfi-eng/sshd-docker#3]
Hi,

i am getting this error at this line

COPY authorized-keys/*.pub /root/.ssh/authorized_keys

Note: /root/.ssh/authorized_keys not a directory to copy.

Also i have modified the docker file as needed.

i am able to login to do ssh fargate container and able to take heapdump, but once i exit from ssh session.

and i am trying to login back again sshd to the same IP or do scp to copy file heapdump to local. it says 

OpenSSH_7.5p1, OpenSSL 1.0.2o  27 Mar 2018
debug1: Reading configuration data /etc/ssh_config
debug1: /etc/ssh_config line 13: Deprecated option "useroaming"
debug2: resolving "10.111.XX.XX" port 22
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to 10.111.XX.XX [10.111.XX.XX] port 22.
debug1: connect to address 10.111.XX.XX port 22: Connection refused
ssh: connect to host 10.111.XX.XX port 22: Connection refused

**Comment by nitsujri** [comment]
@koteshbhupathi Sorry about the slow response!

For the error at line: `COPY authorized-keys/*.pub /root/.ssh/authorized_keys` did you have any public keys in the folder? If it's empty I can see this error being thrown.

It appears something in your ssh_config is overriding/preventing a reconnection to your server. The fact that you can ssh once but not twice appears to point to a config issue. Exactly what, I'm not sure. Wish I could be more help.

**Comment by nitsujri** [comment]
Closing for now - Feel free to respond if it should be reopened.
